# Site title and subtitle. This is used in _includes/header.html
title: 'Podlove'
subtitle: 'Podlove Personal Media Development'

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 2

# URL to source code, used in _includes/footer.html
codeurl: 'http://github.com/podlove'

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: ''

# Dates are not included in permalinks
permalink: /:categories/:title

# Syntax highlighting
highlighter: rouge

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin', 'README.md']

# Use the redcarpet Markdown renderer
markdown: kramdown

kramdown:
  input: GFM # github flavoured markdown
  auto_ids:       true
  # footnote_nr:    1
  entity_output:  as_char
  # toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

playerPath: '/bower_components/podlove-web-player/dist'
